"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['modules/body.py',
              'modules/collision.py',
              'modules/colour.py',
              'modules/constants.py',
              'modules/draw.py',
              'modules/metrics.py',
              'modules/rnd_sphere.py',
              'modules/universe.py',
              'modules/utility.py',
              'modules/vector.py',
              'modules/parser/objects.py',
              'modules/parser/parser.py',
              'modules/parser/special_parsers.py'
              ]
OPTIONS = {
    'iconfile':'icon.icns',
    'argv_emulation':True
}

setup(
    name = "GravitySimulation",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
